import express from 'express';
import { protect } from '../../middleware/Auth.middleware.js';
import { generatePdfReport } from './report.service.js';
import AppError from '../../utils/AppError.js';
import prisma from '../../database/prismaClient.js';

const router = express.Router();

router.use(protect);

const getRoleTypes = (user) => user.roles?.map((role) => role.type) || [];

const getProjectAccess = async (projectId, user) => {
  const project = await prisma.pentest.findUnique({
    where: { id: projectId },
    select: {
      id: true,
      name: true,
      organizationId: true,
      leadPentesterId: true,
      collaborators: { select: { userId: true, role: true } },
    },
  });

  if (!project) {
    throw new AppError('Project not found', 404);
  }

  const userId = user.id;
  const userRoles = getRoleTypes(user);
  const userCollab = project.collaborators.find((collaborator) => collaborator.userId === userId);
  const isLead = project.leadPentesterId === userId;
  const isOrgAdmin = userRoles.includes('ORG_ADMIN');
  const isProjectAdmin = userCollab?.role === 'PROJECT_ADMIN' || userRoles.includes('PROJECT_ADMIN');

  let isOrgAdminMember = false;
  let isOrgMember = false;
  if (project.organizationId) {
    const member = await prisma.organizationMember.findFirst({
      where: { organizationId: project.organizationId, userId },
    });
    isOrgMember = Boolean(member);
    isOrgAdminMember = member?.role === 'owner' || member?.role === 'admin';
  }

  const isCollaborator = Boolean(userCollab);

  return {
    project,
    isCollaborator,
    isLead,
    isOrgAdmin,
    isOrgAdminMember,
    isOrgMember,
    isProjectAdmin,
  };
};

const requireReportManager = async (projectId, user, action = 'generate reports') => {
  const access = await getProjectAccess(projectId, user);
  const isAuthorized = access.isLead || access.isOrgAdmin || access.isOrgAdminMember || access.isProjectAdmin;

  if (!isAuthorized) {
    throw new AppError(`Unauthorized: Only project administrators or organization admins can ${action}`, 403);
  }

  return access;
};

const requireProjectReader = async (projectId, user) => {
  const access = await getProjectAccess(projectId, user);
  const isAuthorized = access.isCollaborator || access.isLead || access.isOrgAdmin || access.isProjectAdmin || access.isOrgMember;

  if (!isAuthorized) {
    throw new AppError('You do not have access to this project', 403);
  }

  return access;
};

const buildReportFilename = (project) => {
  const safeName = (project.name || 'Report')
    .replace(/[^a-z0-9\-_ ]/gi, '')
    .trim()
    .replace(/\s+/g, '-')
    .substring(0, 50);

  return `Hackract-Report-${safeName}-${project.id.split('-')[0].toUpperCase()}.pdf`;
};

/**
 * POST /api/v1/reports/generate
 * Body: { projectId, modules: { execSummary, vulnTable, methodology, rawLogs } }
 * Response: application/pdf binary stream
 */
router.post('/generate', async (req, res, next) => {
  try {
    const { projectId, modules = {} } = req.body;

    if (!projectId) {
      throw new AppError('projectId is required', 400);
    }

    const { project, isOrgAdmin, isOrgAdminMember } = await requireReportManager(projectId, req.user);

    if (isOrgAdmin || isOrgAdminMember) {
      throw new AppError('Organization administrators are not allowed to generate reports.', 403);
    }

    const pdfBuffer = await generatePdfReport(projectId, modules);

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${buildReportFilename(project)}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.setHeader('Cache-Control', 'no-cache');
    res.send(pdfBuffer);
  } catch (err) {
    next(err);
  }
});

/**
 * POST /api/v1/reports/ai-draft
 * Body: { projectId, findingId, prompt, section }
 * Returns structured documentation drafts for project findings generated by the AI assistant.
 */
router.post('/ai-draft', async (req, res, next) => {
  try {
    const { projectId, findingId, prompt: customPrompt, section = 'all' } = req.body;

    if (!projectId) {
      throw new AppError('projectId is required', 400);
    }

    const { project, isOrgAdmin, isOrgAdminMember } = await requireReportManager(projectId, req.user, 'draft report content');

    if (isOrgAdmin || isOrgAdminMember) {
      throw new AppError('Organization administrators are not allowed to draft report content.', 403);
    }

    let findings = [];
    if (findingId) {
      const singleFinding = await prisma.finding.findFirst({
        where: { id: findingId, pentestId: projectId },
      });
      if (!singleFinding) {
        throw new AppError('Finding not found in this project', 404);
      }
      findings = [singleFinding];
    } else {
      findings = await prisma.finding.findMany({
        where: { pentestId: projectId },
        orderBy: [{ severity: 'asc' }, { createdAt: 'desc' }],
      });
    }

    if (findings.length === 0) {
      return res.json({ success: true, data: [] });
    }

    const { generateAssistantResponse } = await import('../AiAssistant/assistant.service.js');
    const systemPrompt = `You are an expert penetration tester and security assistant. Return only valid JSON with these keys: target, description, severityImpact, evidence, remediation.`;
    const results = [];

    for (const finding of findings) {
      let userMessage = `Format this finding:
Title: ${finding.title}
Original Description: ${finding.description || 'N/A'}
Severity: ${finding.severity}
CVSS Score: ${finding.cvssScore || 'N/A'}
Affected Asset: ${finding.affectedAsset || 'N/A'}
Evidence/Proof: ${finding.proof || 'N/A'}
Original Remediation: ${finding.remediation || 'N/A'}
`;

      if (customPrompt) {
        userMessage += section && section !== 'all'
          ? `\nRefine only the "${section}" field using this instruction: ${customPrompt}`
          : `\nAdditional refinement instructions: ${customPrompt}`;
      }

      let aiResult;
      try {
        aiResult = await generateAssistantResponse({
          prompt: userMessage,
          systemPrompt,
          model: process.env.AI_ASSISTANT_MODEL || 'qwen3:0.6b',
        });
      } catch (err) {
        console.error(`AI generation failed for finding ${finding.id}:`, err);
        aiResult = { response: '{}' };
      }

      const fallback = {
        target: finding.affectedAsset || 'N/A',
        description: finding.description || 'N/A',
        severityImpact: `Severity: ${finding.severity}. CVSS: ${finding.cvssScore || 'N/A'}`,
        evidence: finding.proof || 'N/A',
        remediation: finding.remediation || 'N/A',
      };

      let parsed = fallback;
      try {
        const cleanText = aiResult.response
          .trim()
          .replace(/^```(?:json)?/i, '')
          .replace(/```$/, '')
          .trim();

        const parsedJson = JSON.parse(cleanText);
        parsed = {
          target: parsedJson.target || fallback.target,
          description: parsedJson.description || fallback.description,
          severityImpact: parsedJson.severityImpact || parsedJson.severity || fallback.severityImpact,
          evidence: parsedJson.evidence || fallback.evidence,
          remediation: parsedJson.remediation || parsedJson.reremediation || fallback.remediation,
        };
      } catch (parseErr) {
        console.warn('AI response parsing failed. Using finding fallback.', parseErr);
      }

      results.push({
        findingId: finding.id,
        title: finding.title,
        severity: finding.severity,
        cvssScore: finding.cvssScore,
        aiDraft: parsed,
      });
    }

    return res.json({ success: true, data: results });
  } catch (err) {
    next(err);
  }
});

/**
 * POST /api/v1/reports/preview
 * Body: { projectId, modules: { execSummary, vulnTable, methodology, rawLogs } }
 * Response: application/pdf binary stream (browser inline viewing)
 */
router.post('/preview', async (req, res, next) => {
  try {
    const { projectId, modules = {} } = req.body;

    if (!projectId) {
      throw new AppError('projectId is required', 400);
    }

    const { project } = await requireProjectReader(projectId, req.user);

    const pdfBuffer = await generatePdfReport(projectId, modules);

    const safeName = (project.name || 'Report')
      .replace(/[^a-z0-9\-_ ]/gi, '')
      .trim()
      .replace(/\s+/g, '-')
      .substring(0, 50);

    const filename = `Hackract-Report-${safeName}-${projectId.split('-')[0].toUpperCase()}.pdf`;

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `inline; filename="${filename}"`);
    res.setHeader('Content-Length', pdfBuffer.length);
    res.setHeader('Cache-Control', 'no-cache');
    res.send(pdfBuffer);
  } catch (err) {
    next(err);
  }
});

/**
 * GET /api/v1/reports/project/:projectId/json
 * Returns the full report data as structured JSON.
 */
router.get('/project/:projectId/json', async (req, res, next) => {
  try {
    const { projectId } = req.params;
    const { isOrgAdmin, isOrgAdminMember } = await requireReportManager(projectId, req.user, 'export reports');

    if (isOrgAdmin || isOrgAdminMember) {
      throw new AppError('Organization administrators are not allowed to export reports.', 403);
    }

    const project = await prisma.pentest.findUnique({
      where: { id: projectId },
      include: {
        organization: { select: { id: true, name: true } },
        findings: {
          orderBy: [{ severity: 'asc' }, { createdAt: 'desc' }],
          include: { reporter: { select: { fullName: true, handle: true } } },
        },
        collaborators: {
          include: { user: { select: { id: true, fullName: true, handle: true } } },
        },
      },
    });

    if (!project) throw new AppError('Project not found', 404);

    const filename = `Hackract-Report-${projectId.split('-')[0].toUpperCase()}.json`;
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    res.json({ success: true, generatedAt: new Date().toISOString(), data: project });
  } catch (err) {
    next(err);
  }
});

export default router;
