import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { toast } from 'react-hot-toast';
import SignaturePad from '../components/SignaturePad';
import api from '../api/axiosConfig';
import { useAuth } from '../context/authContext';

export default function AgreementExecute() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  
  const roleTypes = user?.roles?.map(r => r.type) || [];
  if (typeof user?.role === 'string') roleTypes.push(user.role);
  const isOrg = roleTypes.some(r => ['SUPER_ADMIN', 'ORG_ADMIN', 'ORGANIZATION'].includes(r));

  const [agreement, setAgreement] = useState(null);
  const [loading, setLoading] = useState(true);
  const [signatureData, setSignatureData] = useState(null);
  const [agreed, setAgreed] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [editableContent, setEditableContent] = useState('');
  const [editableTitle, setEditableTitle] = useState('');

  useEffect(() => {
    const fetchAgreement = async () => {
      try {
        if (id) {
          const res = await api.get(`/legal-agreements/${id}`);
          setAgreement(res.data.data);
          setEditableContent(res.data.data.content || '');
          setEditableTitle(res.data.data.title || '');
        } else {
          // Demo fallback if no ID provided
          const demoContent = `1. SCOPE OF AI SERVICES
This Master Services Agreement ("Agreement") governs the utilization of the Hackract Synthetic Sentinel AI Engine. The User acknowledges that the AI Agent functions as an autonomous vulnerability detection system operating under strict ethical hacking protocols defined in the Project Scope.

The "Synthetic Sentinel" refers to the proprietary neural network architecture utilized for continuous perimeter monitoring and threat neutralization within the User's digital ecosystem.

2. DATA SOVEREIGNTY & PRIVACY
Hackract maintains a zero-knowledge architecture. All cryptographic keys and system logs generated by the AI Agent are encrypted at rest using AES-256-GCM. Hackract shall not have access to the clear-text content of user data unless explicitly authorized through a secondary "Break-Glass" protocol.

User retains all rights, title, and interest in and to all data provided to the AI services. Hackract is granted a limited, non-exclusive license to process such data solely for the purpose of identifying security vulnerabilities.

3. LIABILITY & INDEMNIFICATION
Hackract assumes no liability for system downtime or data loss incurred during the execution of automated exploits, provided that the AI Agent operated within the parameters defined in the pre-approved Rules of Engagement (RoE).

The User agrees to indemnify and hold harmless Hackract from any claims arising out of unauthorized access or collateral damage resulting from the User's failure to patch vulnerabilities identified by the AI Agent within the stipulated grace period.

4. TERMINATION
This Agreement remains in effect until terminated by either party with a 30-day written notice. Upon termination, all active AI Agents assigned to the User's environment will be immediately decommissioned, and all associated telemetry data will be cryptographically shredded.`;

          setAgreement({
            title: "HACKRACT MASTER SERVICES AGREEMENT",
            version: "4.0",
            createdAt: new Date().toISOString(),
            content: demoContent
          });
          setEditableContent(demoContent);
          setEditableTitle("HACKRACT MASTER SERVICES AGREEMENT");
        }
      } catch (err) {
        console.error("Failed to load agreement", err);
        toast.error("Could not load agreement details.");
      } finally {
        setLoading(false);
      }
    };

    fetchAgreement();
  }, [id]);

  const handleSubmit = async () => {
    if (!signatureData) {
      toast.error("Please provide your digital signature.");
      return;
    }
    if (!agreed) {
      toast.error("Please agree to the terms to proceed.");
      return;
    }

    setSubmitting(true);
    try {
      let currentId = id;
      
      // If Org Admin and editing, save or create the agreement
      if (isOrg) {
        if (currentId) {
          await api.patch(`/legal-agreements/${currentId}`, { content: editableContent, title: editableTitle });
        } else {
          // Create new agreement
          const formData = new FormData();
          formData.append('title', editableTitle);
          formData.append('type', "terms_of_service");
          formData.append('content', editableContent);
          formData.append('version', agreement.version);
          formData.append('isActive', true);
          // Just attaching a dummy file for the multer requirement
          const blob = new Blob([editableContent], { type: 'text/plain' });
          formData.append('file', blob, 'agreement.txt');

          const res = await api.post('/legal-agreements', formData, {
            headers: { 'Content-Type': 'multipart/form-data' }
          });
          currentId = res.data.data.id;
        }
      }

      // Now sign it
      if (currentId) {
        await api.post('/user-signatures/sign', {
          agreementId: currentId,
          signatureData
        });
      }
      toast.success(isOrg ? "Agreement saved and signed successfully." : "Agreement executed successfully.");
      setTimeout(() => navigate('/dashboard'), 2000);
    } catch (err) {
      console.error(err);
      toast.error(err.response?.data?.message || "Failed to submit signature.");
      setSubmitting(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <div className="w-8 h-8 border-2 border-[#00c477] border-t-transparent rounded-full animate-spin" />
      </div>
    );
  }

  if (!agreement) return null;

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col md:flex-row overflow-hidden font-sans selection:bg-[#00c477]/30">
      
      {/* Left Panel - Document Viewer */}
      <div className="w-full md:w-1/2 h-screen flex flex-col border-r border-white/[0.05] bg-[#0d0d0d] relative z-10">
        
        {/* Document Header */}
        <div className="px-8 py-6 border-b border-white/[0.05] flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded bg-[#00c477]/10 flex items-center justify-center text-[#00c477]">
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
            </div>
            <span className="text-xs font-mono font-bold text-[#00c477] tracking-widest">
              SERVICE_LEVEL_AGREEMENT_V{agreement.version}.PDF
            </span>
            {isOrg && (
              <span className="ml-2 px-2 py-0.5 rounded text-[10px] bg-amber-500/10 text-amber-500 border border-amber-500/20 font-mono tracking-widest uppercase">
                EDIT MODE
              </span>
            )}
          </div>
          <button className="flex items-center gap-2 px-3 py-1.5 border border-white/10 rounded-md hover:bg-white/5 transition-colors text-xs font-mono tracking-widest text-gray-400 hover:text-white">
            <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            DOWNLOAD AGREEMENT
          </button>
        </div>

        {/* Document Content */}
        <div className="flex-1 overflow-y-auto px-10 py-12 custom-scrollbar">
          <div className="max-w-2xl mx-auto h-full flex flex-col space-y-6">
            {isOrg ? (
              <>
                <div className="bg-[#0c0c0c] border border-white/5 rounded-2xl p-6 lg:p-8 space-y-4">
                  <h2 className="text-xl font-bold text-white">Agreement Title</h2>
                  <input
                    type="text"
                    value={editableTitle}
                    onChange={(e) => setEditableTitle(e.target.value)}
                    className="w-full bg-[#111] border border-[#00c477] rounded-lg p-4 text-sm focus:outline-none text-white font-serif"
                    placeholder="e.g. Master Services Agreement"
                  />
                </div>
                
                <div className="bg-[#0c0c0c] border border-white/5 rounded-2xl p-6 lg:p-8 space-y-4 flex-1 flex flex-col min-h-[50vh]">
                  <h2 className="text-xl font-bold text-white">Agreement Description</h2>
                  <textarea
                    value={editableContent}
                    onChange={(e) => setEditableContent(e.target.value)}
                    className="flex-1 w-full bg-[#111] border border-[#00c477] rounded-lg p-4 text-gray-300 font-mono text-sm leading-relaxed focus:outline-none resize-none custom-scrollbar"
                    placeholder="Enter agreement terms here..."
                  />
                </div>
              </>
            ) : (
              <div>
                <h1 className="text-3xl font-serif font-bold text-white mb-2 leading-tight">
                  {agreement.title}
                </h1>
                <p className="text-[10px] font-mono tracking-widest text-gray-500 mb-8 uppercase">
                  EFFECTIVE DATE: {new Date(agreement.createdAt).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
                </p>
                <div className="prose prose-invert prose-p:text-gray-400 prose-p:leading-relaxed prose-h2:text-white prose-h2:font-serif prose-h2:text-lg prose-h2:mt-8 prose-h2:mb-4">
                  {editableContent.split('\n\n').map((paragraph, idx) => {
                    if (paragraph.trim().match(/^\d+\./)) {
                      return <h2 key={idx}>{paragraph.trim()}</h2>;
                    }
                    if (paragraph.trim() === '') return null;
                    return <p key={idx}>{paragraph.trim()}</p>;
                  })}
                </div>
              </div>
            )}
          </div>
        </div>

      </div>

      {/* Right Panel - Execute & Sign */}
      <div className="w-full md:w-1/2 h-screen flex flex-col relative bg-[#0a0a0a]">
        
        {/* Subtle grid background */}
        <div className="absolute inset-0 pointer-events-none opacity-20" style={{ backgroundImage: 'radial-gradient(circle at center, #ffffff 1px, transparent 1px)', backgroundSize: '24px 24px' }}></div>

        <div className="flex-1 flex flex-col justify-center px-12 lg:px-20 max-w-2xl mx-auto w-full z-10">
          
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
            <h2 className="text-3xl font-bold text-white mb-2">
              {isOrg ? "Edit & Execute Agreement" : "Execute Agreement"}
            </h2>
            <p className="text-xs font-mono text-gray-500 tracking-widest uppercase mb-10">
              VERIFICATION PHASE: FINAL AUTHORIZATION
            </p>

            {/* Signature Box */}
            <div className="w-full h-64 bg-[#111111] border border-white/[0.05] rounded-xl mb-8 relative overflow-hidden shadow-[0_0_30px_rgba(0,196,119,0.02)]">
              {/* Token indicator */}
              <div className="absolute top-4 left-4 flex items-center gap-2 pointer-events-none z-10">
                <div className="w-1.5 h-1.5 rounded-full bg-[#00c477] animate-pulse"></div>
                <span className="text-[10px] font-mono text-[#00c477] tracking-widest">
                  AUTH_TOKEN: #{Math.random().toString(16).slice(2, 6).toUpperCase()}-SEC
                </span>
              </div>

              {/* Signature Pad */}
              <SignaturePad onSignatureChange={setSignatureData} />
            </div>

            {/* Checkbox */}
            <label className="flex items-start gap-4 cursor-pointer group mb-10">
              <div className="relative flex items-center justify-center mt-1">
                <input 
                  type="checkbox" 
                  className="sr-only" 
                  checked={agreed}
                  onChange={(e) => setAgreed(e.target.checked)}
                />
                <div className={`w-5 h-5 rounded border transition-all duration-200 flex items-center justify-center
                  ${agreed ? 'bg-[#00c477] border-[#00c477]' : 'bg-transparent border-gray-600 group-hover:border-gray-400'}
                `}>
                  {agreed && (
                    <svg className="w-3.5 h-3.5 text-[#0a0a0a]" fill="none" stroke="currentColor" strokeWidth="3" viewBox="0 0 24 24">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                  )}
                </div>
              </div>
              <span className="text-sm text-gray-400 leading-relaxed">
                I have read and agree to the terms of the Master Services Agreement. I authorize the activation of the <strong className="text-[#00c477] font-mono font-normal">Hackract AI Agent</strong> within my environment.
              </span>
            </label>

            {/* Submit Button */}
            <button
              onClick={handleSubmit}
              disabled={submitting}
              className={`w-full py-4 rounded-xl font-black tracking-widest uppercase transition-all duration-300
                ${submitting 
                  ? 'bg-[#00c477]/50 text-[#0a0a0a] cursor-not-allowed' 
                  : 'bg-[#00c477] hover:bg-[#00e088] text-[#0a0a0a] hover:shadow-[0_0_30px_rgba(0,196,119,0.4)] hover:-translate-y-0.5'
                }
              `}
            >
              {submitting ? 'EXECUTING...' : (isOrg ? 'SAVE & SIGN' : 'SIGN & SUBMIT')}
            </button>

            <p className="text-[10px] text-center font-mono text-gray-600 tracking-widest mt-4 uppercase">
              TRANSACTION ID: 0XB2F...A109
            </p>
          </motion.div>

        </div>

        {/* Footer Status */}
        <div className="absolute bottom-0 w-full px-6 py-3 border-t border-[#00c477]/10 bg-[#00c477]/5 flex items-center justify-between z-10">
          <div className="flex items-center gap-2">
            <svg className="w-4 h-4 text-[#00c477]" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.956 11.956 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
            </svg>
            <span className="text-[10px] font-mono text-[#00c477]">AI_Agent: System Ready</span>
          </div>
          <div className="flex items-center gap-4 text-[10px] font-mono text-gray-500">
            <span>ENCRYPTION: RSA-4096</span>
            <span>NODE: US-EAST-1</span>
          </div>
        </div>

      </div>

    </div>
  );
}
